# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /lingkong/work/NoNameServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /lingkong/work/NoNameServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /lingkong/work/NoNameServer/CMakeFiles /lingkong/work/NoNameServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /lingkong/work/NoNameServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NonameServer

# Build rule for target.
NonameServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NonameServer
.PHONY : NonameServer

# fast build rule for target.
NonameServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/build
.PHONY : NonameServer/fast

MultiPlayerManager.o: MultiPlayerManager.cpp.o
.PHONY : MultiPlayerManager.o

# target to build an object file
MultiPlayerManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/MultiPlayerManager.cpp.o
.PHONY : MultiPlayerManager.cpp.o

MultiPlayerManager.i: MultiPlayerManager.cpp.i
.PHONY : MultiPlayerManager.i

# target to preprocess a source file
MultiPlayerManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/MultiPlayerManager.cpp.i
.PHONY : MultiPlayerManager.cpp.i

MultiPlayerManager.s: MultiPlayerManager.cpp.s
.PHONY : MultiPlayerManager.s

# target to generate assembly for a file
MultiPlayerManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/MultiPlayerManager.cpp.s
.PHONY : MultiPlayerManager.cpp.s

NonameServer.o: NonameServer.cpp.o
.PHONY : NonameServer.o

# target to build an object file
NonameServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/NonameServer.cpp.o
.PHONY : NonameServer.cpp.o

NonameServer.i: NonameServer.cpp.i
.PHONY : NonameServer.i

# target to preprocess a source file
NonameServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/NonameServer.cpp.i
.PHONY : NonameServer.cpp.i

NonameServer.s: NonameServer.cpp.s
.PHONY : NonameServer.s

# target to generate assembly for a file
NonameServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/NonameServer.cpp.s
.PHONY : NonameServer.cpp.s

NonameServerHttp.o: NonameServerHttp.cpp.o
.PHONY : NonameServerHttp.o

# target to build an object file
NonameServerHttp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/NonameServerHttp.cpp.o
.PHONY : NonameServerHttp.cpp.o

NonameServerHttp.i: NonameServerHttp.cpp.i
.PHONY : NonameServerHttp.i

# target to preprocess a source file
NonameServerHttp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/NonameServerHttp.cpp.i
.PHONY : NonameServerHttp.cpp.i

NonameServerHttp.s: NonameServerHttp.cpp.s
.PHONY : NonameServerHttp.s

# target to generate assembly for a file
NonameServerHttp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/NonameServerHttp.cpp.s
.PHONY : NonameServerHttp.cpp.s

ServerUtils.o: ServerUtils.cpp.o
.PHONY : ServerUtils.o

# target to build an object file
ServerUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/ServerUtils.cpp.o
.PHONY : ServerUtils.cpp.o

ServerUtils.i: ServerUtils.cpp.i
.PHONY : ServerUtils.i

# target to preprocess a source file
ServerUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/ServerUtils.cpp.i
.PHONY : ServerUtils.cpp.i

ServerUtils.s: ServerUtils.cpp.s
.PHONY : ServerUtils.s

# target to generate assembly for a file
ServerUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NonameServer.dir/build.make CMakeFiles/NonameServer.dir/ServerUtils.cpp.s
.PHONY : ServerUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NonameServer"
	@echo "... MultiPlayerManager.o"
	@echo "... MultiPlayerManager.i"
	@echo "... MultiPlayerManager.s"
	@echo "... NonameServer.o"
	@echo "... NonameServer.i"
	@echo "... NonameServer.s"
	@echo "... NonameServerHttp.o"
	@echo "... NonameServerHttp.i"
	@echo "... NonameServerHttp.s"
	@echo "... ServerUtils.o"
	@echo "... ServerUtils.i"
	@echo "... ServerUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

